// Datos ficticios para presentar el catálogo. Precios de ejemplo en ARS.
export const products = [
  {
    slug: 'romero-sal-marina',
    name: 'Focaccia de Romero y Sal Marina',
    description: 'La clásica de masa madre, con aceite de oliva, romero fresco y escamas de sal. Dorada por fuera y bien aireada por dentro.',
    mediumPrice: 6500,
    largePrice: 11000,
    isVeggie: true,
    featured: true,
  },
  {
    slug: 'cherry-albahaca',
    name: 'Focaccia de Cherrys y Albahaca',
    description: 'Tomates cherry asados, albahaca y aceite de oliva sobre nuestra masa de fermentación lenta. Fresca y llena de sabor.',
    mediumPrice: 7500,
    largePrice: 13000,
    isVeggie: true,
    featured: true,
  },
  {
    slug: 'cebolla-morada',
    name: 'Focaccia de Cebolla Morada',
    description: 'Cebolla morada caramelizada, tomillo y oliva. El toque dulce de la cebolla con una base crocante de masa madre.',
    mediumPrice: 7000,
    largePrice: 12000,
    isVeggie: true,
    featured: false,
  },
  {
    slug: 'aceitunas-oregano',
    name: 'Focaccia de Aceitunas y Orégano',
    description: 'Aceitunas verdes y negras, orégano y aceite de oliva. Ideal para acompañar una picada o compartir recién calentita.',
    mediumPrice: 7500,
    largePrice: 13000,
    isVeggie: true,
    featured: false,
  },
  {
    slug: 'cuatro-quesos',
    name: 'Focaccia Cuatro Quesos',
    description: 'Mozzarella, provolone, parmesano y queso azul, gratinados sobre una masa esponjosa. Para quienes siempre quieren más queso.',
    mediumPrice: 9000,
    largePrice: 16000,
    isVeggie: true,
    featured: true,
  },
  {
    slug: 'panceta-cheddar',
    name: 'Focaccia de Panceta y Cheddar',
    description: 'Panceta crocante y cheddar fundido sobre nuestra focaccia de masa madre. Una combinación intensa para darse un gusto.',
    mediumPrice: 9500,
    largePrice: 17000,
    isVeggie: false,
    featured: false,
  },
  {
    slug: 'jamon-rucula',
    name: 'Focaccia de Jamón Crudo y Rúcula',
    description: 'Jamón crudo, rúcula fresca y láminas de parmesano sobre una base dorada con oliva. Un clásico para compartir.',
    mediumPrice: 10500,
    largePrice: 18500,
    isVeggie: false,
    featured: true,
  },
  {
    slug: 'hongos-provolone',
    name: 'Focaccia de Hongos y Provolone',
    description: 'Hongos asados y provolone gratinado sobre masa madre. Cremosa, aromática y con bordes bien crocantes.',
    mediumPrice: 9000,
    largePrice: 16000,
    isVeggie: true,
    featured: false,
  },
];

export const promotions = [
  {
    title: 'Plan de a Dos',
    people: 2,
    description: 'Una focaccia mediana a elección y un dip de la casa para resolver una cena rica y sin vueltas.',
    price: 6900,
    type: 'COMBOS',
    items: [
      { itemType: 'FOCACCIA', label: 'Focaccia a elección', quantity: 1, size: 'MEDIANA' },
      { itemType: 'EXTRA', label: 'Dip de la casa', quantity: 1 },
    ],
  },
  {
    title: 'Mesa Compartida',
    people: 4,
    description: 'Dos focaccias medianas a elección y dos dips. Elegí tus sabores favoritos y compartí.',
    price: 13900,
    type: 'COMBOS',
    items: [
      { itemType: 'FOCACCIA', label: 'Focaccia a elección', quantity: 2, size: 'MEDIANA' },
      { itemType: 'EXTRA', label: 'Dip de la casa', quantity: 2 },
    ],
  },
  {
    title: 'Juntada Crosti',
    people: 8,
    description: 'Dos focaccias grandes a elección y tres dips para poner en el centro de la mesa y disfrutar entre amigos.',
    price: 24900,
    type: 'COMBOS',
    items: [
      { itemType: 'FOCACCIA', label: 'Focaccia a elección', quantity: 2, size: 'GRANDE' },
      { itemType: 'EXTRA', label: 'Dip de la casa', quantity: 3 },
    ],
  },
  {
    title: 'Degustación Crosti',
    people: 6,
    description: 'Tres focaccias medianas para probar distintos sabores. Armá tu selección y encontrá tu favorita.',
    price: 17900,
    type: 'FOCACCIAS',
    items: [
      { itemType: 'FOCACCIA', label: 'Focaccia a elección', quantity: 3, size: 'MEDIANA' },
    ],
  },
  {
    title: 'Noche de Pizza',
    people: 6,
    description: '3 prepizzas de masa madre | Base con salsa de tomate, listas para sumar tus ingredientes | Consultá disponibilidad por WhatsApp',
    price: 9900,
    type: 'PREPIZZAS',
    items: [
      { itemType: 'PREPIZZA', label: 'Prepizza de masa madre con salsa', quantity: 3, size: 'GRANDE' },
    ],
  },
  {
    title: 'Stock para el Finde',
    people: 12,
    description: '6 prepizzas de masa madre | Listas para hornear o guardar en el freezer | Consultá disponibilidad por WhatsApp',
    price: 17900,
    type: 'PREPIZZAS',
    items: [
      { itemType: 'PREPIZZA', label: 'Prepizza de masa madre con salsa', quantity: 6, size: 'GRANDE' },
    ],
  },
];
